package model;

public enum DirecaoEnum {
    CIMA,
    DIREITA,
    BAIXO,
    ESQUERDA,
    CRUZAMENTO_CIMA,
    CRUZAMENTO_DIREITA,
    CRUZAMENTO_BAIXO,
    CRUZAMENTO_ESQUERDA,
    CRUZAMENTO_CIMA_DIREITA,
    CRUZAMENTO_CIMA_ESQUERDA,
    CRUZAMENTO_DIREITA_BAIXO,
    CRUZAMENTO_BAIXO_ESQUERDA;
}